version: "3.9"

services:
  electerm-hoster:
    build:
      context: .
      dockerfile: docker/electerm-hoster.Dockerfile
    image: ghcr.io/adminrealagi/opencodes-binder-webui/electerm-hoster:local
    container_name: electerm-hoster
    ports:
      - "6081:6080"
      - "5901:5900"
    environment:
      - DISPLAY=:99

  opencode-hoster:
    build:
      context: .
      dockerfile: docker/opencode-hoster.Dockerfile
    image: ghcr.io/adminrealagi/opencodes-binder-webui/opencode-hoster:local
    container_name: opencode-hoster
    ports:
      - "6082:6080"
      - "5902:5900"
    environment:
      - DISPLAY=:99
